/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udistrital.avanzada.taller.vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author paisa
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        
        SetImageLabel(lIcono, "src/Imgs/Icono.png"); 
        SetImageLabel(lIconoBoton, "src/Imgs/Icono1.png"); 
        SetImageLabel(lIconoBoton1, "src/Imgs/Icono2.png"); 
        SetImageLabel(lIconoBoton2, "src/Imgs/Icono3.png"); 
        SetImageLabel(lIconoBoton3, "src/Imgs/Icono4.png"); 
        SetImageLabel(lIconoBoton4, "src/Imgs/Icono5.png"); 
        SetImageLabel(lIconoBoton5, "src/Imgs/Icono6.png"); 
//        SetImageLabel(lIconoDos, "src/Imgs/IconoDos.png"); 
    }
    
    private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(),
                        labelName.getHeight(), Image.SCALE_DEFAULT)
        );
        labelName.setIcon(icon);
        this.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lIcono = new javax.swing.JLabel();
        Iconos = new javax.swing.JPanel();
        lIconoBoton = new javax.swing.JLabel();
        lIconoBoton1 = new javax.swing.JLabel();
        lIconoBoton2 = new javax.swing.JLabel();
        lIconoBoton3 = new javax.swing.JLabel();
        lIconoBoton4 = new javax.swing.JLabel();
        botonesArriba = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();
        botonProveedores = new javax.swing.JButton();
        botonItems = new javax.swing.JButton();
        botonVehiculos = new javax.swing.JButton();
        botonAmigos = new javax.swing.JButton();
        botonPerfil = new javax.swing.JButton();
        botonesAbajo = new javax.swing.JPanel();
        botonPerfil1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lIconoBoton5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setLayout(new java.awt.CardLayout());
        jPanel1.add(panelCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 960, 700));

        jPanel2.setBackground(new java.awt.Color(237, 219, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(230, 53, 115));
        jLabel5.setText("Rola PET");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 130, -1));
        jPanel2.add(lIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 130));

        Iconos.setBackground(new java.awt.Color(237, 219, 245));

        lIconoBoton.setMaximumSize(new java.awt.Dimension(50, 50));

        lIconoBoton1.setMaximumSize(new java.awt.Dimension(50, 50));

        lIconoBoton2.setMaximumSize(new java.awt.Dimension(50, 50));

        lIconoBoton3.setMaximumSize(new java.awt.Dimension(50, 50));

        lIconoBoton4.setMaximumSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout IconosLayout = new javax.swing.GroupLayout(Iconos);
        Iconos.setLayout(IconosLayout);
        IconosLayout.setHorizontalGroup(
            IconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIconoBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lIconoBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lIconoBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lIconoBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lIconoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        IconosLayout.setVerticalGroup(
            IconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lIconoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lIconoBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lIconoBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lIconoBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lIconoBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(Iconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 360));

        botonesArriba.setBackground(new java.awt.Color(237, 219, 245));
        botonesArriba.setLayout(new javax.swing.BoxLayout(botonesArriba, javax.swing.BoxLayout.Y_AXIS));

        botonInicio.setBackground(new java.awt.Color(237, 219, 245));
        botonInicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonInicio.setForeground(new java.awt.Color(0, 0, 0));
        botonInicio.setText("Inicio");
        botonInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonInicio.setMaximumSize(new java.awt.Dimension(240, 70));
        botonesArriba.add(botonInicio);

        botonProveedores.setBackground(new java.awt.Color(237, 219, 245));
        botonProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonProveedores.setForeground(new java.awt.Color(0, 0, 0));
        botonProveedores.setText("Proveedores");
        botonProveedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonProveedores.setMaximumSize(new java.awt.Dimension(240, 70));
        botonesArriba.add(botonProveedores);

        botonItems.setBackground(new java.awt.Color(237, 219, 245));
        botonItems.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonItems.setForeground(new java.awt.Color(0, 0, 0));
        botonItems.setText("Items");
        botonItems.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonItems.setMaximumSize(new java.awt.Dimension(240, 70));
        botonesArriba.add(botonItems);

        botonVehiculos.setBackground(new java.awt.Color(237, 219, 245));
        botonVehiculos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        botonVehiculos.setText("Vehiculos");
        botonVehiculos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonVehiculos.setMaximumSize(new java.awt.Dimension(240, 70));
        botonesArriba.add(botonVehiculos);

        botonAmigos.setBackground(new java.awt.Color(237, 219, 245));
        botonAmigos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonAmigos.setForeground(new java.awt.Color(0, 0, 0));
        botonAmigos.setText("Amigos");
        botonAmigos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonAmigos.setMaximumSize(new java.awt.Dimension(240, 70));
        botonesArriba.add(botonAmigos);

        botonPerfil.setBackground(new java.awt.Color(237, 219, 245));
        botonPerfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonPerfil.setForeground(new java.awt.Color(0, 0, 0));
        botonPerfil.setText("Perfil");
        botonPerfil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonPerfil.setMaximumSize(new java.awt.Dimension(240, 70));
        botonesArriba.add(botonPerfil);

        jPanel1.add(botonesArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 170, 500));

        botonesAbajo.setBackground(new java.awt.Color(237, 219, 245));
        botonesAbajo.setLayout(new java.awt.CardLayout());

        botonPerfil1.setBackground(new java.awt.Color(237, 219, 245));
        botonPerfil1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonPerfil1.setForeground(new java.awt.Color(255, 0, 0));
        botonPerfil1.setText("Cerrar Sesión");
        botonPerfil1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonPerfil1.setMaximumSize(new java.awt.Dimension(240, 70));
        botonesAbajo.add(botonPerfil1, "card2");

        jPanel1.add(botonesAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 170, 70));

        jPanel3.setBackground(new java.awt.Color(237, 219, 245));

        lIconoBoton5.setMaximumSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lIconoBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(lIconoBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 70, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Iconos;
    private javax.swing.JButton botonAmigos;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonItems;
    private javax.swing.JButton botonPerfil;
    private javax.swing.JButton botonPerfil1;
    private javax.swing.JButton botonProveedores;
    private javax.swing.JButton botonVehiculos;
    private javax.swing.JPanel botonesAbajo;
    private javax.swing.JPanel botonesArriba;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lIcono;
    private javax.swing.JLabel lIconoBoton;
    private javax.swing.JLabel lIconoBoton1;
    private javax.swing.JLabel lIconoBoton2;
    private javax.swing.JLabel lIconoBoton3;
    private javax.swing.JLabel lIconoBoton4;
    private javax.swing.JLabel lIconoBoton5;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
}
