/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.taller.vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paisa
 */
public class PanelProveedores extends javax.swing.JPanel {

    /**
     * Creates new form PanelProveedores
     */
    public PanelProveedores() {
        initComponents();

        // Crear modelo de tabla con columnas personalizadas
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Nombre", "Tipo", "Ciudad", "Calificación"}
        );

        tablaProveedores.setModel(modelo);

    }

    /**
     * Retorna la tabla de proveedores para poder manipularla desde el
     * controlador.
     *
     * @return JTable de proveedores
     */
    public JTable getTablaProveedores() {
        return tablaProveedores;
    }

    /**
     * Retorna el JTextField de búsqueda de proveedores.
     *
     * @return JTextField de búsqueda
     */
    public JTextField getCajaBuscar() {
        return cajaBuscar;
    }

    /**
     * Retorna el JComboBox para seleccionar el tipo de proveedor.
     *
     * @return JComboBox de tipos de proveedor
     */
    public JComboBox<String> getCajaTipoProveedor() {
        return cajaTipoProveedor;
    }

    /**
     * Retorna el JComboBox para seleccionar el orden de la tabla.
     *
     * @return JComboBox de orden
     */
    public JComboBox<String> getCajaOrden() {
        return cajaOrden;
    }

    /**
     * Retorna el botón de búsqueda de proveedores.
     *
     * @return JButton de buscar
     */
    public JButton getBotonBuscar() {
        return botonBuscar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaBuscar = new javax.swing.JTextField();
        ContenedorTabla = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        cajaOrden = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajaTipoProveedor = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROVEEDORES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 950, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Orden:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, -1));

        cajaBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaBuscar.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        cajaBuscar.setForeground(new java.awt.Color(153, 153, 153));
        cajaBuscar.setBorder(null);
        cajaBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajaBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaBuscarFocusLost(evt);
            }
        });
        cajaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(cajaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 300, -1));

        ContenedorTabla.setBackground(new java.awt.Color(237, 219, 245));

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ContenedorTabla.setViewportView(tablaProveedores);

        jPanel1.add(ContenedorTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 960, 470));

        cajaOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre A-Z", "Nombre Z-A", " " }));
        jPanel1.add(cajaOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 300, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Buscar proveedor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tipo proveedor:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, -1));

        cajaTipoProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Servicios", "Insumos", " " }));
        jPanel1.add(cajaTipoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 300, -1));

        botonBuscar.setBackground(new java.awt.Color(237, 219, 245));
        botonBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonBuscar.setText("BUSCAR");
        botonBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 80, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cajaBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaBuscarFocusGained

    }//GEN-LAST:event_cajaBuscarFocusGained

    private void cajaBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaBuscarFocusLost

    }//GEN-LAST:event_cajaBuscarFocusLost

    private void cajaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ContenedorTabla;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField cajaBuscar;
    private javax.swing.JComboBox<String> cajaOrden;
    private javax.swing.JComboBox<String> cajaTipoProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables
}
