/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udistrital.avanzada.taller.vista;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import udistrital.avanzada.taller.modelo.Evento;

/**
 *
 * @author Paula Martínez
 * @version 1.5 27/09/2025 La clase PanelEventos.java ha sido creada con el fin
 * de mostrar los eventos.
 */
public class PanelEventos extends javax.swing.JPanel {

    /**
     * Creates new form PanelItems
     */
    public PanelEventos() {
        initComponents();
        crearModeloTabla();
    }

    /**
     * Actualiza la tabla con la lista de eventos que le pases
     */
    public void actualizarTabla(List<Evento> lista) {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Titulo", "Descripcion", "Fecha"} // columnas que quieras mostrar
        );

        for (Evento e : lista) {
            modelo.addRow(new Object[]{
                e.getTitulo(),
                e.getDescripcion(),
                e.getFecha() // o el campo que tengas
            });
        }

        tablaEventos.setModel(modelo); // JTable de tu panel
    }

    public JTable getTablaEventos() {
        return tablaEventos;
    }

    public JButton getBtnBuscar() {
        return botonBuscar;
    }

    public String getTextoBusqueda() {
        return cajaBuscar.getText().trim(); // o como tengas tu JTextField
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void crearModeloTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Título", "Descripción", "Fecha"}
        );
        tablaEventos.setModel(modelo);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEventos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cajaBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EVENTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 52, 950, -1));

        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEventos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 193, 962, 507));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Buscar Item:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 158, 200, -1));

        cajaBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaBuscar.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        cajaBuscar.setForeground(new java.awt.Color(153, 153, 153));
        cajaBuscar.setBorder(null);
        cajaBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cajaBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaBuscarFocusLost(evt);
            }
        });
        cajaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(cajaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 300, -1));

        botonBuscar.setBackground(new java.awt.Color(237, 219, 245));
        botonBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonBuscar.setText("BUSCAR");
        botonBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 80, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cajaBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaBuscarFocusGained

    }//GEN-LAST:event_cajaBuscarFocusGained

    private void cajaBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaBuscarFocusLost

    }//GEN-LAST:event_cajaBuscarFocusLost

    private void cajaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField cajaBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEventos;
    // End of variables declaration//GEN-END:variables
}
