/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udistrital.avanzada.taller.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Paula Martínez
 * @version 1.5
 * 23/09/2025
 * La clase Registro.java ha sido creada con el fin de permitir el registro de 
 * los usuarios
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        //Asignamos el logo a unos labels
        SetImageLabel(lIcono, "/Images/Icono.png");
        SetImageLabel(lIconoDos, "/Images/Icono.png");
    }
    
    /**
     * Asigna una imagen a un {@link JLabel}, ajustándola automáticamente 
     * al tamaño actual del componente.
     * <p>
     * La imagen debe estar ubicada en el classpath del proyecto, por ejemplo
     * dentro de <code>src/main/resources</code> en un proyecto Maven, y 
     * la ruta debe comenzar con "/" (ejemplo: <code>"/Images/icono.png"</code>).
     * </p>
     *
     * @param labelName JLabel al que se le va a asignar la imagen.
     * @param path Ruta de la imagen dentro del classpath.
     */
    private void SetImageLabel(JLabel labelName, String path) {
        // Obtiene la ruta de la imagen como recurso dentro del proyecto
        java.net.URL imgURL = getClass().getResource(path);

        // Crea un ImageIcon a partir de la ruta del recurso
        ImageIcon image = new ImageIcon(imgURL);

        // Redimensiona la imagen para que encaje en el JLabel
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(
                        labelName.getWidth(),
                        labelName.getHeight(),
                        Image.SCALE_DEFAULT
                )
        );

        // Asigna el icono redimensionado al JLabel
        labelName.setIcon(icon);

        // Redibuja el contenedor para reflejar el cambio en pantalla
        this.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lIcono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cajaContraseña = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cajaCorreo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        botonRegistro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lIconoDos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(237, 219, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROLA PET - Transporte eléctrico sostenible");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 440, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(230, 53, 115));
        jLabel5.setText("Bienvenido a Rola PET");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 57, 340, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese su información:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, 430, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 210, 290, -1));

        cajaUsuario.setBackground(new java.awt.Color(237, 219, 245));
        cajaUsuario.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        cajaUsuario.setForeground(new java.awt.Color(153, 153, 153));
        cajaUsuario.setText("Ingresa tu usuario");
        cajaUsuario.setBorder(null);
        
        jPanel2.add(cajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 250, 300, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 280, 300, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Correo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 400, 290, -1));

        cajaContraseña.setBackground(new java.awt.Color(237, 219, 245));
        cajaContraseña.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        cajaContraseña.setForeground(new java.awt.Color(153, 153, 153));
        cajaContraseña.setText("Ingresa tu contraseña");
        cajaContraseña.setBorder(null);
        jPanel2.add(cajaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 350, 300, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 380, 300, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Contraseña:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 310, 290, -1));

        cajaCorreo.setBackground(new java.awt.Color(237, 219, 245));
        cajaCorreo.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        cajaCorreo.setForeground(new java.awt.Color(153, 153, 153));
        cajaCorreo.setText("Ingresa tu correo");
        cajaCorreo.setBorder(null);
        
        jPanel2.add(cajaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 435, 300, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 460, 300, 10));

        botonRegistro.setBackground(new java.awt.Color(237, 219, 245));
        botonRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonRegistro.setText("Registrate");
        botonRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 480, 300, 39));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("¿Ya tienes una cuenta?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 530, 190, -1));

        botonIngresar.setBackground(new java.awt.Color(237, 219, 245));
        botonIngresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(153, 153, 255));
        botonIngresar.setText("Inicia Sesión");
        botonIngresar.setBorder(null);
        botonIngresar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jPanel2.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 530, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 600));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(lIconoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 109, 250, 250));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Conéctate con ROLA PET");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 365, 250, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<html><center>  Únete a la comunidad de   <br>transporte eléctrico sostenible  <br> más grande de Colombia y <br> descubre servicios, eventos   <br>y promociones.  </center> </html>");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 388, 250, 92));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 560, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    public javax.swing.JButton botonIngresar;
    public javax.swing.JButton botonRegistro;
    public javax.swing.JTextField cajaContraseña;
    public javax.swing.JTextField cajaCorreo;
    public javax.swing.JTextField cajaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lIcono;
    private javax.swing.JLabel lIconoDos;
    // End of variables declaration                   
}
